package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/AbhishekCS3459/find-me-backend/internal/identity"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/database"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/health"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/middleware"
	"github.com/AbhishekCS3459/find-me-backend/internal/truecaller"
	"github.com/go-chi/chi/v5"
	chiMiddleware "github.com/go-chi/chi/v5/middleware"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "github.com/AbhishekCS3459/find-me-backend/docs" // swagger docs generated by swag
)

// SetupRoutes configures all HTTP routes (exported for testing)
func SetupRoutes(db *database.DB, cfg *Config) *chi.Mux {
	router := chi.NewRouter()

	// Middleware stack (order matters!)
	router.Use(chiMiddleware.RequestID)                 // Add request ID
	router.Use(chiMiddleware.RealIP)                    // Get real IP from X-Forwarded-For
	router.Use(middleware.SecurityHeaders)              // Security headers (X-Frame-Options, CSP, etc.)
	router.Use(middleware.BodyLimit(1 << 20))           // Limit request body to 1MB (DoS protection)
	router.Use(middleware.Metrics)                      // Prometheus metrics collection
	router.Use(middleware.SimpleRequestLogger)          // Structured request logging
	router.Use(middleware.Recoverer)                    // Panic recovery with stack traces
	router.Use(chiMiddleware.Compress(5))               // Response compression
	router.Use(chiMiddleware.Timeout(60 * time.Second)) // Request timeout

	corsConfig := &middleware.CORSConfig{
		AllowedOrigins: []string{
			"http://localhost:3000",
			"http://localhost:5173",
			"https://todayz.in",
			"https://www.todayz.in",
		},
		AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowedHeaders: []string{"Content-Type", "Authorization", "X-API-Token"},
		MaxAge:         3600,
	}
	router.Use(middleware.CORS(corsConfig))

	// Rate limiting (enabled by default, configurable via RATE_LIMIT_ENABLED)
	// Uses token bucket algorithm: allows bursts up to Burst size, then enforces
	// RequestsPerSecond average rate. Each IP gets its own limiter.
	// See middleware/ratelimit.go for detailed implementation notes.
	if cfg.RateLimitEnabled {
		rateLimitConfig := &middleware.RateLimiterConfig{
			RequestsPerSecond: cfg.RateLimitRequestsPerSec,
			Burst:             cfg.RateLimitBurst,
			CleanupInterval:   5 * time.Minute,
			MaxIPs:            10000,
		}
		router.Use(middleware.RateLimit(rateLimitConfig))
	}

	userService := identity.NewService(identity.NewRepository(db.Pool), cfg.JWTSecret)
	healthHandler := health.NewHandler(db)
	identityHandler := identity.NewHandler(userService)
	truecallerHandler := truecaller.NewHandler(truecaller.NewService(truecaller.NewStore(cfg.RedisURL), userService))

	// API Routes
	// Note: API versioning structure ready for expansion
	// Current: /api/v1/... (implicit v1)
	// Future:  /api/v2/... (add version routing)
	router.Route("/api", func(r chi.Router) {
		// Apply JWT auth to all routes (public routes are excluded in the middleware)
		// NOTE: Middleware must be defined BEFORE routes in Chi
		r.Use(middleware.JWTAuth(userService, cfg.APIAccessToken))

		r.Mount("/", healthHandler.Routes())

		// Auth endpoints (public and protected)
		// Apply stricter rate limiting to auth endpoints to prevent brute force attacks.
		// Auth endpoints use HALF the normal rate limit (e.g., 5 req/sec vs 10 req/sec)
		// to make brute force attacks slower and more detectable.
		r.Route("/auth", func(r chi.Router) {
			// Stricter rate limit for authentication endpoints
			if cfg.RateLimitEnabled {
				strictConfig := &middleware.RateLimiterConfig{
					RequestsPerSecond: cfg.RateLimitRequestsPerSec / 2, // Half the normal rate
					Burst:             cfg.RateLimitBurst / 2,
					CleanupInterval:   5 * time.Minute,
					MaxIPs:            10000,
				}
				r.Use(middleware.RateLimit(strictConfig))
			}

			r.Mount("/", identityHandler.AuthRoutes())
		})

		r.Mount("/users", identityHandler.UserRoutes())
		r.Mount("/truecaller", truecallerHandler.Routes())

		// Future: API versioning example
		// r.Route("/v2", func(r chi.Router) {
		// 	r.Route("/users", func(r chi.Router) {
		// 		// v2 endpoints with different structure
		// 	})
		// })
	})

	// Future: Goroutines examples
	// See cmd/api/utils/goroutines.go for common patterns:
	// - BackgroundTask: Fire-and-forget async operations
	// - BackgroundTaskWithRetry: Critical tasks with retry logic
	// - ProcessConcurrently: Worker pool for batch processing
	// - PeriodicTask: Scheduled/recurring tasks
	// - WaitGroupWithTimeout: Coordinating goroutines with timeout
	// - FanOutFanIn: Parallel processing with result collection
	//
	// Example usage in handlers:
	//   // Send welcome email in background (non-blocking)
	//   utils.BackgroundTask(r.Context(), func() error {
	//       return emailService.SendWelcomeEmail(user.Email)
	//   })
	//
	//   // Process multiple users concurrently
	//   err := utils.ProcessConcurrently(r.Context(), users, 5, func(user User) error {
	//       return processUser(user)
	//   })
	//
	//   // Run cleanup task every hour
	//   ctx, cancel := context.WithCancel(context.Background())
	//   defer cancel()
	//   utils.PeriodicTask(ctx, func() error {
	//       return cleanupExpiredTokens()
	//   }, 1*time.Hour)

	// Prometheus metrics endpoint (public, no auth required)
	router.Get("/metrics", promhttp.Handler().ServeHTTP)

	// Swagger UI - dynamically determine URL from request
	router.Get("/swagger/*", func(w http.ResponseWriter, r *http.Request) {
		// Determine scheme (http or https) from request
		scheme := "http"
		if r.TLS != nil || r.Header.Get("X-Forwarded-Proto") == "https" {
			scheme = "https"
		}

		// Get host from request
		host := r.Host
		if host == "" {
			host = "localhost:8080" // fallback for local dev
		}

		// Build Swagger doc.json URL
		swaggerURL := fmt.Sprintf("%s://%s/swagger/doc.json", scheme, host)

		// Use httpSwagger handler with dynamic URL
		httpSwagger.Handler(
			httpSwagger.URL(swaggerURL),
		).ServeHTTP(w, r)
	})

	return router
}
