package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/AbhishekCS3459/find-me-backend/internal/analytics"
	"github.com/AbhishekCS3459/find-me-backend/internal/catalog"
	"github.com/AbhishekCS3459/find-me-backend/internal/identity"
	"github.com/AbhishekCS3459/find-me-backend/internal/identity/progress"
	"github.com/AbhishekCS3459/find-me-backend/internal/identity/retailer"
	"github.com/AbhishekCS3459/find-me-backend/internal/inventory"
	"github.com/AbhishekCS3459/find-me-backend/internal/listproducts"
	"github.com/AbhishekCS3459/find-me-backend/internal/marketplace"
	"github.com/AbhishekCS3459/find-me-backend/internal/marketplace/live"
	"github.com/AbhishekCS3459/find-me-backend/internal/orders"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/database"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/health"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/middleware"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/mongodb"
	"github.com/AbhishekCS3459/find-me-backend/internal/platform/realtime"
	"github.com/AbhishekCS3459/find-me-backend/internal/productcatalog"
	"github.com/AbhishekCS3459/find-me-backend/internal/storeaccess"
	"github.com/AbhishekCS3459/find-me-backend/internal/stores"
	"github.com/AbhishekCS3459/find-me-backend/internal/team"
	"github.com/AbhishekCS3459/find-me-backend/internal/truecaller"
	"github.com/go-chi/chi/v5"
	chiMiddleware "github.com/go-chi/chi/v5/middleware"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/redis/go-redis/v9"
	httpSwagger "github.com/swaggo/http-swagger"
	"go.mongodb.org/mongo-driver/v2/mongo"

	_ "github.com/AbhishekCS3459/find-me-backend/docs" // swagger docs generated by swag
)

// SetupRoutes configures all HTTP routes (exported for testing).
// mongoClient may be nil; catalogue endpoints then respond 503. rdb may be nil
// when Redis is not configured; health then reports it disabled.
// hub carries live inventory changes to open event streams. gateway carries
// availability changes to customers; nil turns live marketplace streams off.
// ordersHandler serves customer orders, store order queues and payment webhooks.
func SetupRoutes(
	db *database.DB, mongoClient *mongodb.Client, rdb *redis.Client, cfg *Config,
	hub *realtime.Hub, gateway *live.Gateway, ordersHandler *orders.Handler,
) *chi.Mux {
	router := chi.NewRouter()

	// Middleware stack (order matters!)
	router.Use(chiMiddleware.RequestID)        // Add request ID
	router.Use(chiMiddleware.RealIP)           // Get real IP from X-Forwarded-For
	router.Use(middleware.SecurityHeaders)     // Security headers (X-Frame-Options, CSP, etc.)
	router.Use(middleware.BodyLimit(1 << 20))  // Limit request body to 1MB (DoS protection)
	router.Use(middleware.Metrics)             // Prometheus metrics collection
	router.Use(middleware.SimpleRequestLogger) // Structured request logging
	router.Use(middleware.Recoverer)           // Panic recovery with stack traces
	router.Use(chiMiddleware.Compress(5))      // Response compression
	// Request timeout; event streams end on their own (see realtime.StreamOptions).
	router.Use(middleware.TimeoutExcept(60*time.Second, func(r *http.Request) bool {
		return inventory.IsEventsRequest(r) || orders.IsEventsRequest(r) || live.IsStreamRequest(r)
	}))

	corsConfig := &middleware.CORSConfig{
		AllowedOrigins: append([]string{
			"http://localhost:3000",
			"http://localhost:5173",
			"https://todayz.in",
			"https://www.todayz.in",
			"https://customer-ui-pearl.vercel.app",
		}, cfg.CORSAllowedOrigins...),
		AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowedHeaders: []string{
			"Content-Type", "Authorization", "X-API-Token", inventory.IdempotencyKeyHeader, marketplace.DebugHeader,
		},
		ExposedHeaders: []string{inventory.IdempotentReplayedHeader},
		MaxAge:         3600,
	}
	router.Use(middleware.CORS(corsConfig))

	// Rate limiting (enabled by default, configurable via RATE_LIMIT_ENABLED)
	// Uses token bucket algorithm: allows bursts up to Burst size, then enforces
	// RequestsPerSecond average rate. Each IP gets its own limiter.
	// See middleware/ratelimit.go for detailed implementation notes.
	if cfg.RateLimitEnabled {
		rateLimitConfig := &middleware.RateLimiterConfig{
			RequestsPerSecond: cfg.RateLimitRequestsPerSec,
			Burst:             cfg.RateLimitBurst,
			CleanupInterval:   5 * time.Minute,
			MaxIPs:            10000,
		}
		router.Use(middleware.RateLimit(rateLimitConfig))
	}

	userService := identity.NewService(identity.NewRepository(db.Pool), cfg.JWTSecret)
	healthHandler := health.NewHandler(db, mongoClient, rdb, cfg.Environment)
	retailerRepo := retailer.NewRepository(db.Gorm)
	retailerService := retailer.NewService(retailerRepo)
	identityHandler := identity.NewHandler(userService, retailerService)
	retailerHandler := retailer.NewHandler(retailerService)
	progressHandler := progress.NewHandler(progress.NewService(progress.NewRepository(db.Gorm)))
	categoryHandler := catalog.NewHandler(catalog.NewService(catalog.NewRepository(db.Gorm)))
	storeAccess := storeaccess.NewResolver(db.Gorm)
	storeHandler := stores.NewHandler(stores.NewService(stores.NewRepository(db.Gorm), retailerRepo, storeAccess))
	var catalogCollection *mongo.Collection
	if mongoClient != nil {
		catalogCollection = mongoClient.Database(cfg.MongoCatalogDatabase).Collection(cfg.MongoCatalogCollection)
	}
	productCatalogService := productcatalog.NewService(productcatalog.NewRepository(catalogCollection))
	productCatalogHandler := productcatalog.NewHandler(productCatalogService)

	inventoryLedger := inventory.NewLedger()
	inventoryHandler := inventory.NewHandler(inventory.NewService(db.Gorm, storeAccess, inventoryLedger), hub)
	listProductsService := listproducts.NewService(
		listproducts.NewRepository(db.Gorm, inventoryLedger), storeAccess, productCatalogService,
	)
	listProductsHandler := listproducts.NewHandler(listProductsService)
	analyticsHandler := analytics.NewHandler(
		analytics.NewService(analytics.NewRepository(db.Gorm), storeAccess, cfg.MarketplaceStaleAfter),
	)
	teamHandler := team.NewHandler(team.NewService(team.NewRepository(db.Gorm), storeAccess))
	truecallerHandler := truecaller.NewHandler(truecaller.NewService(truecaller.NewStore(cfg.RedisURL), userService))
	marketplaceHandler := marketplace.NewHandler(
		marketplace.NewService(marketplace.NewRepository(db.Gorm), marketplace.Config{StaleAfter: cfg.MarketplaceStaleAfter}),
		cfg.MarketplaceDebug,
	)
	marketplaceRoutes := marketplaceHandler.Routes()
	marketplaceRoutes.Get("/products/{catalogKey}/live", live.NewHandler(gateway, live.HandlerConfig{
		MaxPerIP: cfg.MarketplaceLiveMaxPerIP,
		Stream: realtime.StreamOptions{
			Heartbeat:   15 * time.Second,
			MaxLifetime: 10 * time.Minute,
			MinInterval: 500 * time.Millisecond,
			Retry:       3 * time.Second,
		},
	}).Stream)

	// API Routes
	// Note: API versioning structure ready for expansion
	// Current: /api/v1/... (implicit v1)
	// Future:  /api/v2/... (add version routing)
	router.Route("/api", func(r chi.Router) {
		// Apply JWT auth to all routes (public routes are excluded in the middleware)
		// NOTE: Middleware must be defined BEFORE routes in Chi
		r.Use(middleware.JWTAuth(userService, cfg.APIAccessToken))

		r.Mount("/", healthHandler.Routes())

		// Auth endpoints (public and protected)
		// Apply stricter rate limiting to auth endpoints to prevent brute force attacks.
		// Auth endpoints use HALF the normal rate limit (e.g., 5 req/sec vs 10 req/sec)
		// to make brute force attacks slower and more detectable.
		r.Route("/auth", func(r chi.Router) {
			// Stricter rate limit for authentication endpoints
			if cfg.RateLimitEnabled {
				strictConfig := &middleware.RateLimiterConfig{
					RequestsPerSecond: cfg.RateLimitRequestsPerSec / 2, // Half the normal rate
					Burst:             cfg.RateLimitBurst / 2,
					CleanupInterval:   5 * time.Minute,
					MaxIPs:            10000,
				}
				r.Use(middleware.RateLimit(strictConfig))
			}

			r.Mount("/", identityHandler.AuthRoutes())
		})

		r.Mount("/users", identityHandler.UserRoutes())
		r.Mount("/retailers", retailerHandler.Routes())
		r.Mount("/user_progress", progressHandler.Routes())
		r.Mount("/categories", categoryHandler.Routes())
		r.Mount("/catalog", productCatalogHandler.Routes())
		r.Route("/stores/{storeID}/products", func(r chi.Router) {
			r.Mount("/", listProductsHandler.Routes())
		})
		r.Route("/stores/{storeID}/inventory", func(r chi.Router) {
			r.Mount("/", inventoryHandler.Routes())
		})
		r.Route("/stores/{storeID}/analytics", func(r chi.Router) {
			r.Mount("/", analyticsHandler.Routes())
		})
		r.Route("/stores/{storeID}/orders", func(r chi.Router) {
			r.Mount("/", ordersHandler.StoreRoutes())
		})
		r.Mount("/stores", storeHandler.Routes())
		r.Mount("/orders", ordersHandler.CustomerRoutes())
		// Public (see isPublicRoute): gateways sign their webhooks instead.
		r.Mount("/payments/webhooks", ordersHandler.WebhookRoutes())
		r.Mount("/team", teamHandler.Routes())
		r.Mount("/truecaller", truecallerHandler.Routes())
		// Public (see isPublicRoute); under the global rate limit like everything else.
		r.Mount("/marketplace", marketplaceRoutes)

		// Future: API versioning example
		// r.Route("/v2", func(r chi.Router) {
		// 	r.Route("/users", func(r chi.Router) {
		// 		// v2 endpoints with different structure
		// 	})
		// })
	})

	// Future: Goroutines examples
	// See cmd/api/utils/goroutines.go for common patterns:
	// - BackgroundTask: Fire-and-forget async operations
	// - BackgroundTaskWithRetry: Critical tasks with retry logic
	// - ProcessConcurrently: Worker pool for batch processing
	// - PeriodicTask: Scheduled/recurring tasks
	// - WaitGroupWithTimeout: Coordinating goroutines with timeout
	// - FanOutFanIn: Parallel processing with result collection
	//
	// Example usage in handlers:
	//   // Send welcome email in background (non-blocking)
	//   utils.BackgroundTask(r.Context(), func() error {
	//       return emailService.SendWelcomeEmail(user.Email)
	//   })
	//
	//   // Process multiple users concurrently
	//   err := utils.ProcessConcurrently(r.Context(), users, 5, func(user User) error {
	//       return processUser(user)
	//   })
	//
	//   // Run cleanup task every hour
	//   ctx, cancel := context.WithCancel(context.Background())
	//   defer cancel()
	//   utils.PeriodicTask(ctx, func() error {
	//       return cleanupExpiredTokens()
	//   }, 1*time.Hour)

	// Prometheus metrics endpoint (public, no auth required)
	router.Get("/metrics", promhttp.Handler().ServeHTTP)

	// Swagger UI - dynamically determine URL from request
	router.Get("/swagger/*", func(w http.ResponseWriter, r *http.Request) {
		// Determine scheme (http or https) from request
		scheme := "http"
		if r.TLS != nil || r.Header.Get("X-Forwarded-Proto") == "https" {
			scheme = "https"
		}

		// Get host from request
		host := r.Host
		if host == "" {
			host = "localhost:8080" // fallback for local dev
		}

		// Build Swagger doc.json URL
		swaggerURL := fmt.Sprintf("%s://%s/swagger/doc.json", scheme, host)

		// Use httpSwagger handler with dynamic URL
		httpSwagger.Handler(
			httpSwagger.URL(swaggerURL),
		).ServeHTTP(w, r)
	})

	return router
}
